# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8Sn0T4_fWSYVRsDrngQwUIfOKmyhqsS
"""

# Foydalanuvchidan ikkita raqam va amalni olish
num1 = float(input("Birinchi raqamni kiriting: "))
num2 = float(input("Ikkinchi raqamni kiriting: "))
operation = input("Bajariladigan amalni kiriting (qo'shish: +, ayirish: -, ko'paytirish: *, bo'lish: /): ")

# Natijani hisoblash
if operation == "+":
    result = num1 + num2
elif operation == "-":
    result = num1 - num2
elif operation == "*":
    result = num1 * num2
elif operation == "/":
    if num2 != 0:
        result = num1 / num2
    else:
        result = "0 ga bo'la olmaysiz!"
else:
    result = "Noto'g'ri amal kiritildi!"

# Natijani chiqarish
print(f"Natija: {result}")